PROMPT -- aut_USERS
create table aut_users
    ( id            NUMBER(20)           generated by default on null as identity 
    , username      VARCHAR2(50)                                                not null 
    , password      VARCHAR2(256)
    , email         VARCHAR2(100)
    , locked        VARCHAR2(1)         default 'N'                             not null
    , expired       VARCHAR2(1)         default 'Y'                             not NULL
    , logins_failed NUMBER              default 0                               not null 
    , pw_last_upd   DATE                default sysdate                         not null 
    , date_created  DATE                default sysdate                         not null 
    , user_created  VARCHAR2(50)                                                not null 
    , date_modified DATE                default sysdate
    , user_modified VARCHAR2(50)
    , last_call     DATE                                    default sysdate     not NULL 
    , deleted       VARCHAR2(1 CHAR)                        default 'N'         not null
    , parent_usr_id NUMBER
    , primary key(id)
    );
    
create unique index aut_usr_i1 on aut_users(username);

alter table aut_users
        add constraint aut_usr_usr_fk
            foreign key (parent_usr_id) references aut_users (id);
            
create public synonym aut_users for aut_users;

comment on table aut_users is '$Revision: 144624 $';
            