PROMPT -- aut_privileges
create table aut_privileges
    ( id                    NUMBER                      generated by default on null as IDENTITY
    , name                  VARCHAR2(100)               not NULL
    , apex_page             NUMBER                      
    , apex_component_name   VARCHAR2(255) 
    , read                  VARCHAR2(1)  default 'N'    not null
    , write                 VARCHAR2(1)  default 'N'    not null
    , ame_id                NUMBER                      not null
    , primary key(id)
    );
    
create unique index aut_pve_i1 on aut_privileges(name, ame_id);
create unique index aut_pve_i2 on aut_privileges(name, apex_page. apex_component_name, ame_id);
alter table aut_privileges add constraint aut_pve_ame_fk foreign key(ame_id) references 
create public synonym aut_privileges for aut_privileges;